"""add total_amount to orders

Revision ID: 45218e1e231f
Revises: 2bc40823be68
Create Date: 2026-05-26 20:57:20.280945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45218e1e231f'
down_revision = '2bc40823be68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('payment_method', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('delivery_address', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))
        batch_op.drop_column('order_status')
        batch_op.drop_column('total_price')
        batch_op.drop_column('payment_status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_status', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('total_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('order_status', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
        batch_op.drop_column('status')
        batch_op.drop_column('delivery_address')
        batch_op.drop_column('payment_method')
        batch_op.drop_column('total_amount')

    # ### end Alembic commands ###
